# Generated by Django 4.2.17 on 2025-01-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowKeyword',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keyword',),
        ),
        migrations.CreateModel(
            name='WindowKeywordParameter',
            fields=[
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordparameter',),
        ),
        migrations.CreateModel(
            name='WindowKeywordReturnValue',
            fields=[
            ],
            options={
                'verbose_name': 'Return Value',
                'verbose_name_plural': 'Return Value',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordreturnvalue',),
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('documentation', models.TextField(verbose_name='Documentation')),
                ('systems', models.ManyToManyField(related_name='windows', to='systems.system', verbose_name='Systems')),
            ],
            options={
                'verbose_name': 'Window',
                'verbose_name_plural': 'Windows',
            },
        ),
        migrations.CreateModel(
            name='SystemWindow',
            fields=[
            ],
            options={
                'verbose_name': 'Window',
                'verbose_name_plural': 'Windows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('windows.window',),
        ),
        migrations.CreateModel(
            name='WindowDocumentation',
            fields=[
            ],
            options={
                'verbose_name': 'Window documentation',
                'verbose_name_plural': 'Documentation of the windows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('windows.window',),
        ),
    ]
