# Generated by Django 4.2.18 on 2025-02-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowKeyword',
        ),
        migrations.DeleteModel(
            name='WindowKeywordParameter',
        ),
        migrations.DeleteModel(
            name='WindowKeywordReturnValue',
        ),
    ]
