# Generated by Django 4.2.17 on 2025-02-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0002_alter_window_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowKeyword',
        ),
        migrations.DeleteModel(
            name='WindowKeywordParameter',
        ),
        migrations.DeleteModel(
            name='WindowKeywordReturnValue',
        ),
        migrations.CreateModel(
            name='SystemWindow',
            fields=[
            ],
            options={
                'verbose_name': 'Window',
                'verbose_name_plural': 'Windows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('windows.window',),
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': ['name'], 'verbose_name': 'Window', 'verbose_name_plural': 'Windows'},
        ),
    ]
