# Generated by Django 4.2.19 on 2025-02-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0003_delete_windowkeyword_delete_windowkeywordparameter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemWindow',
        ),
        migrations.CreateModel(
            name='WindowQuickAdd',
            fields=[
            ],
            options={
                'verbose_name': 'Window',
                'verbose_name_plural': 'Windows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('windows.window',),
        ),
    ]
