# Generated by Django 4.2.18 on 2025-03-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0004_delete_systemwindow_windowquickadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindowQuickChange',
            fields=[
            ],
            options={
                'verbose_name': 'Window',
                'verbose_name_plural': 'Windows',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('windows.window',),
        ),
    ]
