# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_alter_system_options_alter_system_attach_to_system_and_more'),
        ('windows', '0005_windowquickchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': ['name'], 'verbose_name': 'Maske', 'verbose_name_plural': 'Masken'},
        ),
        migrations.AlterModelOptions(
            name='windowdocumentation',
            options={'verbose_name': 'Dokumentation der Maske', 'verbose_name_plural': 'Dokumentation der Masken'},
        ),
        migrations.AlterModelOptions(
            name='windowquickadd',
            options={'verbose_name': 'Maske', 'verbose_name_plural': 'Masken'},
        ),
        migrations.AlterModelOptions(
            name='windowquickchange',
            options={'verbose_name': 'Maske', 'verbose_name_plural': 'Masken'},
        ),
        migrations.AlterField(
            model_name='window',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='window',
            name='documentation',
            field=models.TextField(verbose_name='Dokumentation'),
        ),
        migrations.AlterField(
            model_name='window',
            name='systems',
            field=models.ManyToManyField(related_name='windows', to='systems.system', verbose_name='Systeme'),
        ),
    ]
