# Generated by Django 4.2.21 on 2025-06-06 12:02

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0006_alter_window_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Maske', 'verbose_name_plural': 'Masken'},
        ),
    ]
