# Generated by Django 4.2.17 on 2025-01-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('attach_to_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.keyword', verbose_name='Attach to a running system')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.library', verbose_name='Automation')),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
        ),
    ]
