# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_alter_library_options_alter_libraryimport_options_and_more'),
        ('keywords', '0023_alter_executionkeywordcall_options_and_more'),
        ('systems', '0003_remove_system_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={},
        ),
        migrations.AlterField(
            model_name='system',
            name='attach_to_system',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.keyword', verbose_name='Anbindung an laufendes System'),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='system',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.library', verbose_name='Automatisierung'),
        ),
    ]
