# Generated by Django 4.2.21 on 2025-05-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_alter_system_options_alter_system_attach_to_system_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['name'], 'verbose_name': 'System', 'verbose_name_plural': 'Systeme'},
        ),
    ]
