# Generated by Django 4.2.21 on 2025-06-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0025_keywordcallparameter_robot_variable'),
        ('systems', '0005_alter_system_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='attach_to_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.keyword', verbose_name='Anbindung an laufendes System'),
        ),
    ]
