# Generated by Django 4.2.21 on 2025-06-06 12:02

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_alter_system_attach_to_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'System', 'verbose_name_plural': 'Systeme'},
        ),
    ]
