# Generated by Django 5.2.12 on 2026-10-05 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0064_alter_keyword_last_unlocked'),
        ('systems', '0007_alter_system_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='attach_to_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_systems', to='keywords.keyword', verbose_name='Anbindung an laufendes System'),
        ),
    ]
