# Generated by Django 4.2.17 on 2025-01-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('documentation', models.TextField(verbose_name='Documentation')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceKeyword',
            fields=[
            ],
            options={
                'verbose_name': 'Resource Keyword',
                'verbose_name_plural': 'Resource Keywords',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keyword',),
        ),
        migrations.CreateModel(
            name='ResourceKeywordDocumentation',
            fields=[
            ],
            options={
                'verbose_name': 'Documentation of the resource keyword',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.resourcekeyword',),
        )
    ]
