# Generated by Django 4.2.16 on 2024-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords', '0001_initial'),
        ('executions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('documentation', models.TextField(verbose_name='Dokumentation')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressourcen',
            },
        ),
        migrations.CreateModel(
            name='ResourceKeyword',
            fields=[
            ],
            options={
                'verbose_name': 'Ressource-Schlüsselwort',
                'verbose_name_plural': 'Ressource-Schlüsselwörter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keyword',),
        ),
        migrations.CreateModel(
            name='ResourceKeywordDocumentation',
            fields=[
            ],
            options={
                'verbose_name': 'Dokumentation des Ressource-Schlüsselworts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.resourcekeyword',),
        )
    ]
