# Generated by Django 4.2.18 on 2025-02-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_delete_executionlibraryimport_and_more'),
        ('keywords', '0002_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FROM_EXECUTION', 'From an Execution'), ('FROM_SEQUENCE', 'From a Sequence')], max_length=255)),
                ('execution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_imports', to='executions.execution')),
                ('keyword', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_imports', to='keywords.keyword')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='Resource')),
            ],
            options={
                'verbose_name': 'Resource Import',
                'verbose_name_plural': 'Resource Imports',
            },
        ),
        migrations.AddConstraint(
            model_name='resourceimport',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'FROM_EXECUTION'), ('execution__isnull', False), ('keyword__isnull', True)), models.Q(('type', 'FROM_SEQUENCE'), ('execution__isnull', True), ('keyword__isnull', False)), _connector='OR'), name='resource_import_sum_type'),
        ),
        migrations.AddConstraint(
            model_name='resourceimport',
            constraint=models.UniqueConstraint(condition=models.Q(('execution__isnull', False)), fields=('execution', 'resource'), name='unique_execution_resource_import'),
        ),
        migrations.AddConstraint(
            model_name='resourceimport',
            constraint=models.UniqueConstraint(condition=models.Q(('keyword__isnull', False)), fields=('keyword', 'resource'), name='unique_keyword_resource_import'),
        ),
    ]
