# Generated by Django 4.2.17 on 2025-01-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(
                    choices=[('FROM_EXECUTION', 'Aus einer Ausführung'), ('FROM_SEQUENCE', 'Aus einer Sequenz')],
                    max_length=255)),
                ('execution',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='resource_imports', to='executions.execution')),
                ('keyword',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='resource_imports', to='keywords.keyword')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource',
                                               verbose_name='Ressource')),
            ],
            options={
                'verbose_name': 'Ressource-Import',
                'verbose_name_plural': 'Ressource-Imports',
            },
        ),
        migrations.AddConstraint(
            model_name='resourceimport',
            constraint=models.CheckConstraint(check=models.Q(
                models.Q(('type', 'FROM_EXECUTION'), ('execution__isnull', False), ('keyword__isnull', True)),
                models.Q(('type', 'FROM_SEQUENCE'), ('execution__isnull', True), ('keyword__isnull', False)),
                _connector='OR'), name='resource_import_sum_type'),
        ),
        migrations.AddConstraint(
            model_name='resourceimport',
            constraint=models.UniqueConstraint(condition=models.Q(('execution__isnull', False)),
                                               fields=('execution', 'resource'),
                                               name='unique_execution_resource_import'),
        ),
        migrations.AddConstraint(
            model_name='resourceimport',
            constraint=models.UniqueConstraint(condition=models.Q(('keyword__isnull', False)),
                                               fields=('keyword', 'resource'), name='unique_keyword_resource_import'),
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourceimport',
            options={'verbose_name': 'Resource Import', 'verbose_name_plural': 'Resource Imports'},
        ),
        migrations.AlterModelOptions(
            name='resourcekeyword',
            options={'verbose_name': 'Resource Keyword', 'verbose_name_plural': 'Resource Keywords'},
        ),
        migrations.AlterModelOptions(
            name='resourcekeyworddocumentation',
            options={'verbose_name': 'Documentation of the resource keyword'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='documentation',
            field=models.TextField(verbose_name='Documentation'),
        ),
        migrations.AlterField(
            model_name='resourceimport',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='Resource'),
        ),
        migrations.AlterField(
            model_name='resourceimport',
            name='type',
            field=models.CharField(choices=[('FROM_EXECUTION', 'From an Execution'), ('FROM_SEQUENCE', 'From a Sequence')], max_length=255),
        ),
    ]
