# Generated by Django 4.2.17 on 2025-02-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_options_alter_resourceimport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceimport',
            options={'ordering': ['resource__name'], 'verbose_name': 'Resource Import', 'verbose_name_plural': 'Resource Imports'},
        ),
    ]
