# Generated by Django 4.2.19 on 2025-03-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0004_delete_systemwindow_windowquickadd'),
        ('resources', '0003_alter_resourceimport_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourceimport',
            name='resource_import_sum_type',
        ),
        migrations.RemoveConstraint(
            model_name='resourceimport',
            name='unique_keyword_resource_import',
        ),
        migrations.RemoveField(
            model_name='resourceimport',
            name='keyword',
        ),
        migrations.AddField(
            model_name='resourceimport',
            name='window',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_imports', to='windows.window'),
        ),
        migrations.AlterField(
            model_name='resourceimport',
            name='type',
            field=models.CharField(choices=[('FROM_EXECUTION', 'From an Execution'), ('FROM_WINDOW', 'Aus einer Maske')], max_length=255),
        ),
        migrations.AddConstraint(
            model_name='resourceimport',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'FROM_EXECUTION'), ('execution__isnull', False), ('window__isnull', True)), models.Q(('type', 'FROM_WINDOW'), ('execution__isnull', True), ('window__isnull', False)), _connector='OR'), name='resource_import_sum_type'),
        ),
        migrations.AddConstraint(
            model_name='resourceimport',
            constraint=models.UniqueConstraint(condition=models.Q(('window__isnull', False)), fields=('window', 'resource'), name='unique_window_resource_import'),
        ),
    ]
