# Generated by Django 4.2.19 on 2025-03-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_remove_resourceimport_resource_import_sum_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
