# Generated by Django 4.2.19 on 2025-03-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name'], 'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
    ]
