# Generated by Django 4.2.19 on 2025-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_resource_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
