# Generated by Django 4.2.18 on 2025-03-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_resource_name_alter_resource_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceKeyword',
        ),
        migrations.DeleteModel(
            name='ResourceKeywordDocumentation',
        ),
    ]
