# Generated by Django 4.2.20 on 2025-04-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_delete_resourcekeyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceimport',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.resource', verbose_name='Resource'),
        ),
    ]
