# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_alter_resourceimport_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['name'], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressourcen'},
        ),
        migrations.AlterModelOptions(
            name='resourceimport',
            options={'ordering': ['resource__name'], 'verbose_name': 'Ressource-Import', 'verbose_name_plural': 'Ressource-Imports'},
        ),
        migrations.AlterField(
            model_name='resource',
            name='documentation',
            field=models.TextField(verbose_name='Dokumentation'),
        ),
        migrations.AlterField(
            model_name='resourceimport',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.resource', verbose_name='Ressource'),
        ),
        migrations.AlterField(
            model_name='resourceimport',
            name='type',
            field=models.CharField(choices=[('FROM_EXECUTION', 'Aus einer Ausführung'), ('FROM_WINDOW', 'Aus einer Maske')], max_length=255),
        ),
    ]
