# Generated by Django 4.2.21 on 2025-06-06 12:02

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_resource_options_alter_resourceimport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Ressource', 'verbose_name_plural': 'Ressourcen'},
        ),
    ]
