# Generated by Django 4.2.21 on 2025-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_resource_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resourceimport',
            name='resource_import_sum_type',
        ),
    ]
