# Generated by Django 4.2.17 on 2025-01-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('windows', '0001_initial'),
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('systems', models.ManyToManyField(related_name='variables', to='systems.system', verbose_name='Systems')),
                ('windows', models.ManyToManyField(related_name='variables', to='windows.window', verbose_name='Windows')),
            ],
            options={
                'verbose_name': 'Reference Value',
                'verbose_name_plural': 'Reference Values',
            },
        ),
        migrations.CreateModel(
            name='VariableValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variables.variable')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
            },
        ),
        migrations.CreateModel(
            name='WindowVariable',
            fields=[
            ],
            options={
                'verbose_name': 'Reference Value',
                'verbose_name_plural': 'Reference Values',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('variables.variable',),
        ),
        migrations.AddConstraint(
            model_name='variablevalue',
            constraint=models.UniqueConstraint(fields=('variable', 'name'), name='unique_value_per_variable'),
        ),
    ]
