# Generated by Django 4.2.19 on 2025-02-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0006_alter_variable_systems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowVariable',
        ),
        migrations.CreateModel(
            name='VariableQuickAdd',
            fields=[
            ],
            options={
                'verbose_name': 'Reference Value',
                'verbose_name_plural': 'Reference Values',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('variables.variable',),
        ),
    ]
