# Generated by Django 4.2.18 on 2025-02-27 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0004_delete_systemwindow_windowquickadd'),
        ('variables', '0007_delete_windowvariable_variablequickadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('windows', models.ManyToManyField(related_name='schemas', to='windows.window', verbose_name='Windows')),
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemas',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Dictionary'), ('LIST', 'List')], default='DICT', max_length=255),
        ),
        migrations.CreateModel(
            name='VariableSchemaField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='variables.variableschema')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('list_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='variables.variable')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_list', to='variables.variable')),
            ],
            options={
                'ordering': ['index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableSchemaQuickAdd',
            fields=[
            ],
            options={
                'verbose_name': 'Schema',
                'verbose_name_plural': 'Schemata',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('variables.variableschema',),
        ),
        migrations.AddField(
            model_name='variable',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variableschema'),
        ),
    ]
