# Generated by Django 4.2.18 on 2025-02-28 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0008_variableschema_variable_type_variableschemafield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableDocumentation',
            fields=[
            ],
            options={
                'verbose_name': 'Reference Value',
                'verbose_name_plural': 'Reference Values',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('variables.variable',),
        ),
        migrations.AddField(
            model_name='variablevalue',
            name='list_variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='variables.variable'),
        ),
    ]
