# Generated by Django 4.2.18 on 2025-02-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0009_variabledocumentation_variablevalue_list_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Name-Wert Paaren'), ('LIST', 'Tabelle')], default='DICT', max_length=255, verbose_name='Datenstruktur'),
        ),
    ]
