# Generated by Django 4.2.18 on 2025-03-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0010_alter_variable_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variableschema',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterModelOptions(
            name='variableschemaquickadd',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterField(
            model_name='variable',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variableschema', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Record'), ('LIST', 'Table')], default='DICT', max_length=255, verbose_name='Datenstruktur'),
        ),
        migrations.AlterField(
            model_name='variableinlist',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_list', to='variables.variable', verbose_name='Reference Value'),
        ),
    ]
