# Generated by Django 4.2.18 on 2025-03-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0011_alter_variableschema_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablevalue',
            name='schema_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variableschemafield'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='variables.variableschema', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Record'), ('LIST', 'Table')], default='DICT', max_length=255, verbose_name='Data Structure'),
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='list_variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variable'),
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='variables.variable'),
        ),
    ]
