# Generated by Django 4.2.18 on 2025-03-05 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0012_variablevalue_schema_field_alter_variable_schema_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variablevalue',
            name='unique_value_per_variable',
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Eine Instanz'), ('LIST', 'Mehrere Instanzen')], default='DICT', max_length=255),
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='schema_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='variables.variableschemafield'),
        ),
    ]
