# Generated by Django 4.2.18 on 2025-03-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0013_remove_variablevalue_unique_value_per_variable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Eine Instanz'), ('LIST', 'Mehrere Instanzen')], default='DICT', max_length=255, verbose_name='Menge'),
        ),
    ]
