# Generated by Django 4.2.18 on 2025-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0014_alter_variable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'One instance'), ('LIST', 'Several instances')], default='DICT', max_length=255, verbose_name='Quantity'),
        ),
    ]
