# Generated by Django 4.2.18 on 2025-03-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0015_alter_variable_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableQuickChange',
            fields=[
            ],
            options={
                'verbose_name': 'Reference Value',
                'verbose_name_plural': 'Reference Values',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('variables.variable',),
        ),
    ]
