# Generated by Django 4.2.18 on 2025-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0016_variablequickchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['name'], 'verbose_name': 'Reference Value', 'verbose_name_plural': 'Reference Values'},
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Value'),
        ),
    ]
