# Generated by Django 4.2.20 on 2025-04-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0017_alter_variable_options_alter_variablevalue_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variableschemafield',
            options={'ordering': ['index'], 'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AddField(
            model_name='variableschemafield',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
