# Generated by Django 4.2.20 on 2025-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0018_alter_variableschemafield_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variablevalue',
            constraint=models.UniqueConstraint(fields=('variable', 'name'), name='unique_variable_value_name'),
        ),
    ]
