# Generated by Django 4.2.20 on 2025-05-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0019_variablevalue_unique_variable_value_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variableschemafield',
            constraint=models.UniqueConstraint(fields=('schema', 'name'), name='unique_field_per_schema'),
        ),
    ]
