# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0006_alter_window_options_and_more'),
        ('systems', '0004_alter_system_options_alter_system_attach_to_system_and_more'),
        ('variables', '0020_variableschemafield_unique_field_per_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['name'], 'verbose_name': 'Referenzwert', 'verbose_name_plural': 'Referenzwerte'},
        ),
        migrations.AlterModelOptions(
            name='variabledocumentation',
            options={'verbose_name': 'Referenzwert', 'verbose_name_plural': 'Referenzwerte'},
        ),
        migrations.AlterModelOptions(
            name='variablequickadd',
            options={'verbose_name': 'Referenzwert', 'verbose_name_plural': 'Referenzwerte'},
        ),
        migrations.AlterModelOptions(
            name='variablequickchange',
            options={'verbose_name': 'Referenzwert', 'verbose_name_plural': 'Referenzwerte'},
        ),
        migrations.AlterModelOptions(
            name='variableschema',
            options={'verbose_name': 'Vorlage', 'verbose_name_plural': 'Vorlagen'},
        ),
        migrations.AlterModelOptions(
            name='variableschemafield',
            options={'ordering': ['index'], 'verbose_name': 'Feld', 'verbose_name_plural': 'Felder'},
        ),
        migrations.AlterModelOptions(
            name='variableschemaquickadd',
            options={'verbose_name': 'Vorlage', 'verbose_name_plural': 'Vorlagen'},
        ),
        migrations.AlterModelOptions(
            name='variablevalue',
            options={'verbose_name': 'Wert', 'verbose_name_plural': 'Werte'},
        ),
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='variables.variableschema', verbose_name='Vorlage'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='systems',
            field=models.ManyToManyField(related_name='variables', to='systems.system', verbose_name='Systeme'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Eine Instanz'), ('LIST', 'Mehrere Instanzen')], default='DICT', max_length=255, verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='windows',
            field=models.ManyToManyField(related_name='variables', to='windows.window', verbose_name='Masken'),
        ),
        migrations.AlterField(
            model_name='variableinlist',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_list', to='variables.variable', verbose_name='Referenzwert'),
        ),
        migrations.AlterField(
            model_name='variableschema',
            name='windows',
            field=models.ManyToManyField(related_name='schemas', to='windows.window', verbose_name='Masken'),
        ),
        migrations.AlterField(
            model_name='variablevalue',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Wert'),
        ),
    ]
