# Generated by Django 4.2.21 on 2025-06-06 12:02

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0021_alter_variable_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Referenzwert', 'verbose_name_plural': 'Referenzwerte'},
        ),
    ]
