# Generated by Django 4.2.21 on 2025-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0022_alter_variable_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='template',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
