# Generated by Django 4.2.21 on 2025-06-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0023_variable_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variableschema',
            options={'verbose_name': 'Datenvorlage', 'verbose_name_plural': 'Datenvorlagen'},
        ),
        migrations.AlterModelOptions(
            name='variableschemaquickadd',
            options={'verbose_name': 'Datenvorlage', 'verbose_name_plural': 'Datenvorlagen'},
        ),
        migrations.AlterField(
            model_name='variable',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='variables.variableschema', verbose_name='Datenvorlage'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='template',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vorlage'),
        ),
    ]
