# Generated by Django 4.2.21 on 2025-07-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0024_alter_variableschema_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variablevalue',
            options={'ordering': ['schema_field__index'], 'verbose_name': 'Wert', 'verbose_name_plural': 'Werte'},
        ),
    ]
