# Generated by Django 4.2.21 on 2025-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0036_remove_keywordcallparametersource_variable_schema_field_and_more'),
        ('variables', '0025_alter_variablevalue_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariableSchemaQuickAdd',
        ),
        migrations.AlterModelOptions(
            name='variablevalue',
            options={'ordering': ['index'], 'verbose_name': 'Wert', 'verbose_name_plural': 'Werte'},
        ),
        migrations.RemoveField(
            model_name='variable',
            name='schema',
        ),
        migrations.RemoveField(
            model_name='variablevalue',
            name='schema_field',
        ),
        migrations.AddField(
            model_name='variablevalue',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='VariableSchema',
        ),
        migrations.DeleteModel(
            name='VariableSchemaField',
        ),
    ]
