# Generated by Django 4.2.21 on 2025-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0026_remove_variableschema_windows_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variablevalue',
            name='list_variable',
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Formular'), ('LIST', 'Tabelle')], default='DICT', max_length=255, verbose_name='Art'),
        ),
        migrations.DeleteModel(
            name='VariableInList',
        ),
    ]
