# Generated by Django 4.2.21 on 2025-09-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0027_remove_variablevalue_list_variable_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variablevalue',
            name='unique_variable_value_name',
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Formular'), ('LIST', 'Werteliste')], default='DICT', max_length=255, verbose_name='Art'),
        ),
    ]
