# Generated by Django 4.2.21 on 2025-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0028_remove_variablevalue_unique_variable_value_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableWindowRelation',
            fields=[
            ],
            options={
                'verbose_name': 'Referenzwert',
                'verbose_name_plural': 'Referenzwerte',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('variables.variable_windows', models.Model),
        ),
    ]
