# Generated by Django 5.2.7 on 2025-10-08 07:35

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0029_variablewindowrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableColumn',
            fields=[
            ],
            options={
                'verbose_name': 'Spalte',
                'verbose_name_plural': 'Spalten',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('variables.variable',),
        ),
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ['index', django.db.models.functions.text.Lower('name')], 'verbose_name': 'Referenzwert', 'verbose_name_plural': 'Referenzwerte'},
        ),
        migrations.AddField(
            model_name='variable',
            name='index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variable',
            name='table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='variables.variable', verbose_name='Tabelle'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='type',
            field=models.CharField(choices=[('DICT', 'Formular'), ('LIST', 'Werteliste'), ('TABLE', 'Tabelle')], default='DICT', max_length=255, verbose_name='Art'),
        ),
    ]
