# Generated by Django 5.2.12 on 2026-08-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0030_tablecolumn_alter_variable_options_variable_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='setup_teardown',
            field=models.BooleanField(default=False, verbose_name='Vor-/Nachbereitung'),
        ),
    ]
