# Generated by Django 5.2.12 on 2026-08-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0031_variable_setup_teardown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
            ],
            options={
                'verbose_name': 'Tabelle',
                'verbose_name_plural': 'Tabellen',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('variables.variable',),
        ),
    ]
