# Generated by Django 4.2.17 on 2025-01-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_doc', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('args_doc', models.TextField(blank=True, verbose_name='Parameters')),
                ('documentation', models.TextField(blank=True, verbose_name='Documentation')),
                ('type', models.CharField(choices=[('LIBRARY', 'Keyword from Library'), ('RESOURCE', 'Keyword from Resource'), ('ACTION', 'Action'), ('SEQUENCE', 'Sequence')], max_length=255)),
                ('setup_teardown', models.BooleanField(default=False, verbose_name='Setup/Teardown')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='')),
                ('index', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('type', models.CharField(choices=[('KEYWORD_CALL', 'Keyword Call'), ('KEYWORD_EXECUTION', 'Keyword Execution'), ('TEST_STEP', 'Test Step'), ('TEST_SETUP', 'Test Setup'), ('TEST_TEARDOWN', 'Test Teardown'), ('SUITE_SETUP', 'Suite Setup'), ('SUITE_TEARDOWN', 'Suite Teardown')], max_length=255)),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='KeywordCallParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='KeywordCallReturnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('keyword_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_value', to='keywords.keywordcall')),
                ('return_value', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordcallreturnvalue')),
            ],
            options={
                'verbose_name': 'Return Value',
            },
        ),
        migrations.CreateModel(
            name='KeywordReturnValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_value', to='keywords.keyword')),
                ('kw_call_return_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordcallreturnvalue', verbose_name='Return Value')),
            ],
            options={
                'verbose_name': 'Return Value',
                'verbose_name_plural': 'Return Value',
            },
        ),
        migrations.CreateModel(
            name='KeywordParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('position', models.PositiveIntegerField(default=0, null=True)),
                ('default_value', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Default Value')),
                ('is_list', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('ARG', 'Positional Argument'), ('KWARG', 'Optional Argument')], max_length=255)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='keywords.keyword')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='KeywordCallParameterSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KEYWORD_PARAMETER', 'Keyword Parameters'), ('KW_CALL_RETURN_VALUE', 'Call Return Value'), ('VARIABLE_VALUE', 'Reference Value')], max_length=255)),
                ('kw_call_ret_val', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordcallreturnvalue')),
                ('kw_param', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordparameter')),
            ],
            options={
                'verbose_name': 'Parameter reference',
                'verbose_name_plural': 'Parameter references',
            },
        ),
    ]
