# Generated by Django 4.2.18 on 2025-02-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='everywhere',
        ),
    ]
