# Generated by Django 4.2.17 on 2025-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_remove_keyword_everywhere'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionKeywordCall',
            fields=[
            ],
            options={
                'verbose_name': 'Call Parameters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
        migrations.AlterModelOptions(
            name='keywordcallparameter',
            options={'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.AddField(
            model_name='keywordreturnvalue',
            name='kw_call_index',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
