# Generated by Django 4.2.18 on 2025-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0006_robotkeywordcall_alter_keyword_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keywordcall',
            constraint=models.UniqueConstraint(models.F('execution'), models.F('type'), models.F('user'), name='unique_keyword_call_type_per_execution_per_user'),
        ),
    ]
