# Generated by Django 4.2.18 on 2025-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0007_keywordcall_unique_keyword_call_type_per_execution_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordcall',
            name='unique_keyword_call_type_per_execution_per_user',
        ),
        migrations.RemoveField(
            model_name='keywordcall',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='keywordcall',
            constraint=models.UniqueConstraint(models.F('execution'), models.F('type'), name='unique_keyword_call_type_per_execution'),
        ),
    ]
