# Generated by Django 4.2.18 on 2025-02-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0009_remove_keywordcall_unique_keyword_call_type_per_execution_per_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WindowKeywordParameter',
        ),
        migrations.DeleteModel(
            name='WindowKeywordReturnValue',
        ),
    ]
