# Generated by Django 4.2.18 on 2025-02-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0001_initial'),
        ('keywords', '0009_delete_windowkeywordparameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordcall',
            name='variable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variable', verbose_name='Reference Values'),
        ),
    ]
