# Generated by Django 4.2.18 on 2025-02-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0010_alter_variable_type'),
        ('keywords', '0011_keywordcall_variable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordcallparametersource',
            name='kw_call_parameter_source_sum_type',
        ),
        migrations.AddField(
            model_name='keywordcallparametersource',
            name='variable_schema_field',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variableschemafield'),
        ),
        migrations.AlterField(
            model_name='keywordcallparametersource',
            name='type',
            field=models.CharField(choices=[('KEYWORD_PARAMETER', 'Keyword Parameters'), ('KW_CALL_RETURN_VALUE', 'Call Return Value'), ('VARIABLE_VALUE', 'Reference Value'), ('VARIABLE_SCHEMA_FIELD', 'Schemafeld')], max_length=255),
        ),
        migrations.AddConstraint(
            model_name='keywordcallparametersource',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('type', 'KEYWORD_PARAMETER'), ('kw_param__isnull', False), ('kw_call_ret_val__isnull', True), ('variable_schema_field__isnull', True), ('variable_value__isnull', True)), models.Q(('type', 'KW_CALL_RETURN_VALUE'), ('kw_param__isnull', True), ('kw_call_ret_val__isnull', False), ('variable_schema_field__isnull', True), ('variable_value__isnull', True)), models.Q(('type', 'VARIABLE_SCHEMA_FIELD'), ('kw_param__isnull', True), ('kw_call_ret_val__isnull', True), ('variable_schema_field__isnull', False), ('variable_value__isnull', True)), models.Q(('type', 'VARIABLE_VALUE'), ('kw_param__isnull', True), ('kw_call_ret_val__isnull', True), ('variable_schema_field__isnull', True), ('variable_value__isnull', False)), _connector='OR'), name='kw_call_parameter_source_sum_type'),
        ),
    ]
