# Generated by Django 4.2.18 on 2025-03-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0012_remove_keywordcallparametersource_kw_call_parameter_source_sum_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallparametersource',
            name='type',
            field=models.CharField(choices=[('KEYWORD_PARAMETER', 'Keyword Parameters'), ('KW_CALL_RETURN_VALUE', 'Call Return Value'), ('VARIABLE_VALUE', 'Reference Value'), ('VARIABLE_SCHEMA_FIELD', 'Template Field')], max_length=255),
        ),
    ]
