# Generated by Django 4.2.18 on 2025-03-05 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0001_initial'),
        ('keywords', '0013_alter_keywordcallparametersource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcall',
            name='variable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variable', verbose_name='Reference Values (optional)'),
        ),
    ]
