# Generated by Django 4.2.18 on 2025-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0014_alter_keywordcall_variable'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordcall',
            name='condition',
            field=models.CharField(default='', max_length=255),
        ),
    ]
