# Generated by Django 4.2.18 on 2025-03-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0015_keywordcall_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcall',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bedingung (optional)'),
        ),
    ]
