# Generated by Django 4.2.18 on 2025-03-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0016_extend_json_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcall',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Condition (optional)'),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='to_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='keywords.keyword'),
        ),
    ]
