# Generated by Django 4.2.18 on 2025-03-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0017_alter_keywordcall_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallreturnvalue',
            name='keyword_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_values', to='keywords.keywordcall'),
        ),
    ]
