# Generated by Django 4.2.18 on 2025-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0018_alter_keywordcallreturnvalue_keyword_call_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordcallparameter',
            options={'ordering': ['parameter__position'], 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
        migrations.RemoveConstraint(
            model_name='keywordparameter',
            name='keyword_parameter_sum_type',
        ),
        migrations.AlterField(
            model_name='keywordparameter',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
