# Generated by Django 4.2.18 on 2025-03-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0019_alter_keywordcallparameter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallparameter',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Value'),
        ),
    ]
