# Generated by Django 4.2.20 on 2025-04-23 13:10

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0020_alter_keywordcallparameter_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
