# Generated by Django 4.2.20 on 2025-05-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0020_variableschemafield_unique_field_per_schema'),
        ('keywords', '0021_alter_keyword_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcall',
            name='variable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variable', verbose_name='Reference Value (optional)'),
        ),
    ]
