# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('windows', '0005_windowquickchange'),
        ('libraries', '0007_alter_library_options_alter_libraryimport_options_and_more'),
        ('variables', '0020_variableschemafield_unique_field_per_schema'),
        ('resources', '0010_alter_resource_options_alter_resourceimport_options_and_more'),
        ('systems', '0003_remove_system_client'),
        ('keywords', '0022_alter_keywordcall_variable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionkeywordcall',
            options={'verbose_name': 'Aufrufparameter'},
        ),
        migrations.AlterModelOptions(
            name='keywordcall',
            options={'ordering': ['index'], 'verbose_name': 'Schritt', 'verbose_name_plural': 'Schritte'},
        ),
        migrations.AlterModelOptions(
            name='keywordcallparametersource',
            options={'verbose_name': 'Parameter-Referenz', 'verbose_name_plural': 'Parameter-Referenzen'},
        ),
        migrations.AlterModelOptions(
            name='keywordcallreturnvalue',
            options={'verbose_name': 'Rückgabewert'},
        ),
        migrations.AlterModelOptions(
            name='keywordreturnvalue',
            options={'verbose_name': 'Rückgabewert', 'verbose_name_plural': 'Rückgabewert'},
        ),
        migrations.AlterModelOptions(
            name='robotkeywordcall',
            options={'verbose_name': 'Schritt', 'verbose_name_plural': 'Schritte'},
        ),
        migrations.AlterModelOptions(
            name='teststep',
            options={'verbose_name': 'Schritt', 'verbose_name_plural': 'Schritte'},
        ),
        migrations.AlterField(
            model_name='keyword',
            name='documentation',
            field=models.TextField(blank=True, verbose_name='Dokumentation'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='library',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='libraries.library', verbose_name='Bibliothek'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='resources.resource', verbose_name='Ressource'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='setup_teardown',
            field=models.BooleanField(default=False, verbose_name='Vor-/Nachbereitung'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='short_doc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='systems',
            field=models.ManyToManyField(related_name='keywords', to='systems.system', verbose_name='Systeme'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='type',
            field=models.CharField(choices=[('LIBRARY', 'Schlüsselwort aus Bibliothek'), ('RESOURCE', 'Schlüsselwort aus Ressource'), ('ACTION', 'Aktion'), ('SEQUENCE', 'Sequenz')], max_length=255),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='windows',
            field=models.ManyToManyField(related_name='keywords', to='windows.window', verbose_name='Maske'),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Bedingung (optional)'),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='type',
            field=models.CharField(choices=[('KEYWORD_CALL', 'Schlüsselwort-Aufruf'), ('KEYWORD_EXECUTION', 'Schlüsselwort Ausführung'), ('TEST_STEP', 'Testschritt'), ('TEST_SETUP', 'Testvorbereitung'), ('TEST_TEARDOWN', 'Testnachbereitung'), ('SUITE_SETUP', 'Suitevorbereitung'), ('SUITE_TEARDOWN', 'Suitenachbereitung')], max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='variable',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variable', verbose_name='Referenzwert (optional)'),
        ),
        migrations.AlterField(
            model_name='keywordcall',
            name='window',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='windows.window', verbose_name='Maske'),
        ),
        migrations.AlterField(
            model_name='keywordcallparameter',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Wert'),
        ),
        migrations.AlterField(
            model_name='keywordcallparametersource',
            name='type',
            field=models.CharField(choices=[('KEYWORD_PARAMETER', 'Schlüsselwort-Parameter'), ('KW_CALL_RETURN_VALUE', 'Aufrufs-Rückgabewert'), ('VARIABLE_VALUE', 'Referenzwert'), ('VARIABLE_SCHEMA_FIELD', 'Schemafeld')], max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordparameter',
            name='default_value',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Standardwert'),
        ),
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='kw_call_return_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordcallreturnvalue', verbose_name='Rückgabewert'),
        ),
    ]
