# Generated by Django 4.2.21 on 2025-05-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0023_alter_executionkeywordcall_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RobotKeywordCall',
        ),
        migrations.CreateModel(
            name='LibraryKeywordCall',
            fields=[
            ],
            options={
                'verbose_name': 'Schritt',
                'verbose_name_plural': 'Schritte',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
    ]
