# Generated by Django 4.2.21 on 2025-06-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0024_delete_robotkeywordcall_librarykeywordcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordcallparameter',
            name='robot_variable',
            field=models.BooleanField(default=False),
        ),
    ]
