# Generated by Django 4.2.20 on 2025-06-04 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0025_keywordcallparameter_robot_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_values', to='keywords.keyword'),
        ),
    ]
