# Generated by Django 4.2.21 on 2025-06-10 12:36

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0026_alter_keywordreturnvalue_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Schlüsselwort', 'verbose_name_plural': 'Schlüsselwörter'},
        ),
    ]
