# Generated by Django 4.2.21 on 2025-06-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0027_alter_keyword_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyword',
            name='unique_keyword_per_library',
        ),
        migrations.RemoveConstraint(
            model_name='keyword',
            name='unique_keyword_per_resource',
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(condition=models.Q(('library__isnull', False)), fields=('library', 'name'), name='unique_keyword_per_library'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(condition=models.Q(('resource__isnull', False)), fields=('resource', 'name'), name='unique_keyword_per_resource'),
        ),
    ]
