# Generated by Django 4.2.21 on 2025-06-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0028_remove_keyword_unique_keyword_per_library_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordcall',
            name='unique_keyword_call_type_per_execution',
        ),
        migrations.AddConstraint(
            model_name='keywordcall',
            constraint=models.UniqueConstraint(fields=('execution', 'type'), name='unique_keyword_call_type_per_execution'),
        ),
    ]
