# Generated by Django 4.2.21 on 2025-06-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0029_remove_keywordcall_unique_keyword_call_type_per_execution_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordcall',
            name='unique_keyword_call_type_per_execution',
        ),
        migrations.AddConstraint(
            model_name='keywordcall',
            constraint=models.UniqueConstraint(condition=models.Q(('execution__isnull', False)), fields=('execution', 'type'), name='unique_keyword_call_type_per_execution'),
        ),
    ]
