# Generated by Django 4.2.21 on 2025-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0030_remove_keywordcall_unique_keyword_call_type_per_execution_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyword',
            name='keyword_sum_type',
        ),
        migrations.RemoveConstraint(
            model_name='keywordcall',
            name='keyword_call_sum_type',
        ),
        migrations.RemoveConstraint(
            model_name='keywordcallparametersource',
            name='kw_call_parameter_source_sum_type',
        ),
    ]
