# Generated by Django 4.2.21 on 2025-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0031_remove_keyword_keyword_sum_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallparameter',
            name='robot_variable',
            field=models.CharField(choices=[('DICTIONARY_ITEM', 'dict.item -> ${dict}[item]')], max_length=255),
        ),
    ]
