# Generated by Django 4.2.21 on 2025-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0032_alter_keywordcallparameter_robot_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallparameter',
            name='robot_variable',
            field=models.CharField(blank=True, choices=[('DICTIONARY_ITEM', 'dict.item -> ${dict}[item]')], max_length=255, verbose_name='Format (optional)'),
        ),
    ]
