# Generated by Django 4.2.21 on 2025-07-28 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0033_alter_keywordcallparameter_robot_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcall',
            name='condition',
        ),
        migrations.CreateModel(
            name='KeywordCallCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('in', 'enthält'), ('==', 'ist'), ('!=', 'ist nicht')], max_length=255, verbose_name='Bedingung')),
                ('expected_value', models.CharField(blank=True, max_length=255, verbose_name='Soll Wert')),
                ('keyword_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='keywords.keywordcall')),
                ('value_ref', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keywords.keywordcallparametersource', verbose_name='Wert')),
            ],
            options={
                'verbose_name': 'Bedingung',
                'verbose_name_plural': 'Bedingungen',
            },
        ),
    ]
