# Generated by Django 4.2.21 on 2025-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0034_remove_keywordcall_condition_keywordcallcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallcondition',
            name='condition',
            field=models.CharField(choices=[('in', 'enthält'), ('not in', 'enthält nicht'), ('==', 'ist'), ('!=', 'ist nicht')], max_length=255, verbose_name='Bedingung'),
        ),
    ]
