# Generated by Django 4.2.21 on 2025-07-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0034_remove_keywordcall_condition_keywordcallcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallcondition',
            name='condition',
            field=models.CharField(choices=[('=', 'Ist'), ('!=', 'Ist nicht')], max_length=255, verbose_name='Bedingung'),
        ),
        migrations.AlterField(
            model_name='keywordcallcondition',
            name='expected_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Soll Wert'),
        ),
    ]
