# Generated by Django 4.2.21 on 2025-07-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0035_alter_keywordcallcondition_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallcondition',
            name='condition',
            field=models.CharField(choices=[('in', 'ist Teil von'), ('==', 'ist'), ('!=', 'ist nicht')], max_length=255, verbose_name='Bedingung'),
        ),
    ]
