# Generated by Django 4.2.21 on 2025-08-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0035_alter_keywordcallcondition_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordcallreturnvalue',
            old_name='return_value',
            new_name='kw_call_return_value',
        ),
        migrations.AddField(
            model_name='keywordreturnvalue',
            name='typedoc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='kw_call_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='kw_call_return_value',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordcallreturnvalue', verbose_name='Rückgabewert'),
        ),
    ]
