# Generated by Django 4.2.21 on 2025-08-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0036_rename_return_value_keywordcallreturnvalue_kw_call_return_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordcallreturnvalue',
            name='return_value',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='keywords.keywordreturnvalue'),
        ),
    ]
