# Generated by Django 4.2.21 on 2025-07-28 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0036_alter_keywordcallcondition_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcallcondition',
            name='keyword_parameter',
        ),
        migrations.AddField(
            model_name='keywordcallcondition',
            name='value_ref',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='keywords.keywordcallparametersource'),
            preserve_default=False,
        ),
    ]
