# Generated by Django 4.2.21 on 2025-07-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0037_keywordcallreturnvalue_return_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcallparameter',
            name='robot_variable',
        ),
    ]
