# Generated by Django 4.2.21 on 2025-08-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0038_remove_keywordcallparameter_robot_variable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordparameter',
            name='is_list',
        ),
        migrations.AlterField(
            model_name='keywordparameter',
            name='type',
            field=models.CharField(choices=[('ARG', 'Positional Argument'), ('KWARG', 'Optional Argument'), ('VARARG', 'Variadic Argument')], max_length=255),
        ),
    ]
