# Generated by Django 4.2.21 on 2025-08-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0039_remove_keywordparameter_is_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcallcondition',
            name='expected_value_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_values', to='keywords.keywordcallparametersource'),
        ),
        migrations.AlterField(
            model_name='keywordcallcondition',
            name='value_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='keywords.keywordcallparametersource', verbose_name='Wert'),
        ),
    ]
