# Generated by Django 4.2.21 on 2025-07-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0040_alter_keywordcallcondition_expected_value_ref_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcallparametersource',
            name='variable_schema_field',
        ),
        migrations.AlterField(
            model_name='keywordcallparametersource',
            name='type',
            field=models.CharField(choices=[('KEYWORD_PARAMETER', 'Schlüsselwort-Parameter'), ('KW_CALL_RETURN_VALUE', 'Aufrufs-Rückgabewert'), ('VARIABLE_VALUE', 'Referenzwert')], max_length=255),
        ),
    ]
