# Generated by Django 4.2.21 on 2025-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0041_remove_keywordcallparametersource_variable_schema_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordparameter',
            name='typedoc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
