# Generated by Django 4.2.21 on 2025-08-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0042_keywordparameter_typedoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordparameter',
            name='typedoc',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
