# Generated by Django 4.2.21 on 2025-08-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0043_alter_keywordparameter_typedoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='args_doc',
        ),
    ]
