# Generated by Django 4.2.21 on 2025-08-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0044_remove_keyword_args_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryKeywordCallParameter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcallparameter',),
        ),
        migrations.AddField(
            model_name='keywordreturnvalue',
            name='type',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
