# Generated by Django 4.2.21 on 2025-08-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0045_librarykeywordcallparameter_keywordreturnvalue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='type',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='typedoc',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
