# Generated by Django 4.2.21 on 2025-08-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0046_alter_keywordreturnvalue_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='type',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='typedoc',
            field=models.TextField(default=None, null=True),
        ),
    ]
