# Generated by Django 4.2.21 on 2025-09-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0047_alter_keywordreturnvalue_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordreturnvalue',
            options={'verbose_name': 'Rückgabewert', 'verbose_name_plural': 'Rückgabewerte'},
        ),
    ]
