# Generated by Django 4.2.21 on 2025-09-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0047_alter_keywordreturnvalue_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordreturnvalue',
            options={'verbose_name': 'Rückgabewert', 'verbose_name_plural': 'Rückgabewerte'},
        ),
        migrations.RemoveField(
            model_name='keywordcallreturnvalue',
            name='kw_call_return_value',
        ),
        migrations.AlterField(
            model_name='keywordcallreturnvalue',
            name='return_value',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='keywords.keywordreturnvalue'),
        ),
        migrations.AlterField(
            model_name='keywordreturnvalue',
            name='kw_call_return_value',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='keywords.keywordcallreturnvalue', verbose_name='Rückgabewert'),
        ),
    ]
