# Generated by Django 4.2.21 on 2025-09-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0048_alter_keywordreturnvalue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordcallparameter',
            options={'ordering': ['parameter__position'], 'verbose_name': 'Eingabewert', 'verbose_name_plural': 'Eingabewerte'},
        ),
    ]
