# Generated by Django 4.2.21 on 2025-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0049_alter_keywordcallparameter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordcall',
            name='execute',
            field=models.BooleanField(default=False, verbose_name='▶'),
        ),
    ]
