# Generated by Django 4.2.21 on 2025-09-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0050_keywordcall_execute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestStep',
        ),
        migrations.AlterModelOptions(
            name='executionkeywordcall',
            options={'verbose_name': 'Eingabewerte'},
        ),
    ]
