# Generated by Django 5.2.6 on 2025-09-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0051_delete_teststep_alter_executionkeywordcall_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordcallreturnvalue',
            options={'verbose_name': 'Rückgabewert', 'verbose_name_plural': 'Rückgabewerte'},
        ),
    ]
