# Generated by Django 5.2.6 on 2025-10-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0052_alter_keywordcallreturnvalue_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryKeywordCall',
        ),
        migrations.DeleteModel(
            name='LibraryKeywordCallParameter',
        ),
    ]
