# Generated by Django 5.2.7 on 2025-10-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0053_delete_librarykeywordcall_and_more'),
        ('variables', '0030_tablecolumn_alter_variable_options_variable_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordcallparametersource',
            name='table_column',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='variables.variable'),
        ),
        migrations.AlterField(
            model_name='keywordcallparametersource',
            name='type',
            field=models.CharField(choices=[('KEYWORD_PARAMETER', 'Schlüsselwort-Parameter'), ('KW_CALL_RETURN_VALUE', 'Aufrufs-Rückgabewert'), ('TABLE_COLUMN', 'Spalte'), ('VARIABLE_VALUE', 'Referenzwert')], max_length=255),
        ),
    ]
