# Generated by Django 5.2.7 on 2025-10-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0056_remove_keywordcall_execute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcall',
            name='execution_state',
            field=models.CharField(choices=[('EXECUTE', '☑ Execute'), ('DO_NOT_EXECUTE', '◻ Skip'), ('BEGIN_EXECUTION', '🔽 Execute from this step'), ('END_EXECUTION', '🔼 Ausführen bis')], default='EXECUTE', max_length=255, verbose_name='Ausf.'),
        ),
    ]
