# Generated by Django 5.2.7 on 2025-10-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0056_remove_keywordcall_execute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcall',
            name='execution_state',
            field=models.CharField(choices=[('EXECUTE', 'EXECUTE'), ('SKIP_EXECUTION', 'SKIP_EXECUTION'), ('BEGIN_EXECUTION', 'BEGIN_EXECUTION'), ('END_EXECUTION', 'END_EXECUTION')], default='EXECUTE', max_length=255, verbose_name='Ausf.'),
        ),
    ]
