# Generated by Django 5.2.7 on 2025-10-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0057_alter_keywordcall_execution_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordcall',
            name='execution_state',
            field=models.CharField(choices=[('EXECUTE', 'EXECUTE'), ('DO_NOT_EXECUTE', 'DO_NOT_EXECUTE'), ('BEGIN_EXECUTION', 'BEGIN_EXECUTION'), ('END_EXECUTION', 'END_EXECUTION')], default='EXECUTE', max_length=255, verbose_name='Ausf.'),
        ),
    ]
