# Generated by Django 5.2.7 on 2025-10-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0057_alter_keywordcall_execution_state'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordcall',
            name='unique_keyword_call_type_per_execution',
        ),
    ]
