# Generated by Django 5.2.7 on 2025-11-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0058_remove_keywordcall_unique_keyword_call_type_per_execution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcall',
            name='execution_state',
        ),
    ]
