# Generated by Django 5.2.11 on 2026-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0059_remove_keywordcall_execution_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordparameter',
            name='type',
            field=models.CharField(choices=[('ARG', 'Positional Argument'), ('KWARG', 'Optional Argument'), ('VAR_ARG', 'Variadic Argument'), ('VAR_KWARG', 'Variadic Named Argument')], max_length=255),
        ),
    ]
