# Generated by Django 5.2.11 on 2026-02-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0060_alter_keywordparameter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordparameter',
            name='kind',
            field=models.CharField(default='POSITIONAL_OR_NAMED', max_length=255),
        ),
        migrations.AlterField(
            model_name='keywordcallparameter',
            name='value_ref',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kw_call_parameters', to='keywords.keywordcallparametersource'),
        ),
        migrations.AlterField(
            model_name='keywordcallparametersource',
            name='kw_call_ret_val',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kw_call_ret_val_source', to='keywords.keywordcallreturnvalue'),
        ),
        migrations.AlterField(
            model_name='keywordcallparametersource',
            name='kw_param',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kw_param_source', to='keywords.keywordparameter'),
        ),
    ]
