# Generated by Django 5.2.11 on 2026-02-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0061_keywordparameter_kind_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keywordparameter',
            name='unique_keyword_parameter',
        ),
    ]
