# Generated by Django 5.2.11 on 2026-03-01 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0062_remove_keywordparameter_unique_keyword_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='last_unlocked',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 28, 10, 2, 28, 554944, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='keyword',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
