# Generated by Django 5.2.12 on 2026-10-05 07:31

import keyta.apps.keywords.models.keyword
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0008_userexecution_stop_on_failure'),
        ('keywords', '0063_keyword_last_unlocked_keyword_locked'),
        ('testcases', '0010_alter_testcase_options'),
        ('windows', '0007_alter_window_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='last_unlocked',
            field=models.DateTimeField(default=keyta.apps.keywords.models.keyword.yesterday),
        )
    ]
