# Generated by Django 5.2.12 on 2026-10-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0008_userexecution_stop_on_failure'),
        ('keywords', '0064_alter_keyword_last_unlocked'),
        ('testcases', '0010_alter_testcase_options'),
        ('windows', '0007_alter_window_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='keywordcall',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('testcase__isnull', False), ('window__isnull', False)), models.Q(('testcase__isnull', True), ('window__isnull', True)), _connector='OR'), name='teststep_has_window'),
        ),
    ]
