# Generated by Django 4.2.17 on 2025-01-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KEYWORD_EXECUTION', 'Keyword Execution'), ('TESTCASE_EXECUTION', 'Test Case Execution')], max_length=255)),
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Execution',
            },
        ),
        migrations.CreateModel(
            name='UserExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[('PASS', 'Successful'), ('FAIL', 'Failed')], default=None, max_length=255, null=True, verbose_name='Result')),
                ('log', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Log')),
                ('running', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User-related execution',
                'verbose_name_plural': 'User-related executions',
            },
        ),
    ]
