# Generated by Django 4.2.18 on 2025-02-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_initial'),
        ('executions', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutionLibraryImport',
        ),
        migrations.DeleteModel(
            name='KeywordExecutionCall',
        ),
        migrations.DeleteModel(
            name='KeywordExecutionSetup',
        ),
        migrations.DeleteModel(
            name='SetupTeardown',
        ),
        migrations.DeleteModel(
            name='TestCaseExecutionSetupTeardown',
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
            ],
            options={
                'verbose_name': 'Vorbereitung',
                'verbose_name_plural': 'Vorbereitung',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
        migrations.CreateModel(
            name='Teardown',
            fields=[
            ],
            options={
                'verbose_name': 'Nachbereitung',
                'verbose_name_plural': 'Nachbereitung',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
        migrations.AlterField(
            model_name='execution',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
