# Generated by Django 4.2.17 on 2025-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0005_executionkeywordcall_teststep_and_more'),
        ('executions', '0003_alter_execution_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecutionLibraryImport',
        ),
        migrations.DeleteModel(
            name='ExecutionResourceImport',
        ),
        migrations.DeleteModel(
            name='KeywordExecutionCall',
        ),
        migrations.DeleteModel(
            name='KeywordExecutionSetup',
        ),
        migrations.DeleteModel(
            name='SetupTeardown',
        ),
        migrations.DeleteModel(
            name='TestCaseExecutionSetupTeardown',
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setup',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
        migrations.CreateModel(
            name='Teardown',
            fields=[
            ],
            options={
                'verbose_name': 'Teardown',
                'verbose_name_plural': 'Teardown',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
        migrations.CreateModel(
            name='TestCaseExecution',
            fields=[
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Execution',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('executions.execution',),
        ),
        migrations.AlterField(
            model_name='execution',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
