# Generated by Django 4.2.17 on 2025-02-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_delete_executionlibraryimport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
        migrations.AlterModelOptions(
            name='teardown',
            options={'verbose_name': 'Teardown', 'verbose_name_plural': 'Teardown'},
        ),
    ]
