# Generated by Django 4.2.17 on 2025-01-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_alter_execution_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseExecution',
            fields=[
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Execution',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('executions.execution',),
        ),
    ]
