# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('executions', '0004_delete_executionlibraryimport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'verbose_name': 'Ausführung', 'verbose_name_plural': 'Ausführung'},
        ),
        migrations.AlterModelOptions(
            name='keywordexecution',
            options={'verbose_name': 'Ausführung', 'verbose_name_plural': 'Ausführung'},
        ),
        migrations.AlterModelOptions(
            name='setup',
            options={'verbose_name': 'Vorbereitung', 'verbose_name_plural': 'Vorbereitung'},
        ),
        migrations.AlterModelOptions(
            name='teardown',
            options={'verbose_name': 'Nachbereitung', 'verbose_name_plural': 'Nachbereitung'},
        ),
        migrations.AlterModelOptions(
            name='testcaseexecution',
            options={'verbose_name': 'Ausführung', 'verbose_name_plural': 'Ausführung'},
        ),
        migrations.AlterModelOptions(
            name='userexecution',
            options={'verbose_name': 'Benutzer-bezogene Ausführung', 'verbose_name_plural': 'Benutzer-bezogene Ausführungen'},
        ),
        migrations.AlterField(
            model_name='userexecution',
            name='log',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Protokoll'),
        ),
        migrations.AlterField(
            model_name='userexecution',
            name='result',
            field=models.CharField(blank=True, choices=[('PASS', 'Erfolgreich'), ('FAIL', 'Fehlgeschlagen')], default=None, max_length=255, null=True, verbose_name='Ergebnis'),
        ),
        migrations.AlterField(
            model_name='userexecution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
    ]
