# Generated by Django 4.2.21 on 2025-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_alter_execution_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='execution',
            name='execution_sum_type',
        ),
    ]
