# Generated by Django 5.2.8 on 2025-11-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0006_remove_execution_execution_sum_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexecution',
            name='running',
        ),
    ]
