# Generated by Django 5.2.8 on 2026-02-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0007_remove_userexecution_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexecution',
            name='stop_on_failure',
            field=models.BooleanField(default=True, verbose_name='Beim 1. Fehler abbrechen'),
        ),
    ]
