# Generated by Django 5.2.11 on 2026-03-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0008_userexecution_stop_on_failure'),
        ('testcases', '0011_testdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexecution',
            name='testdata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testcases.testdata', verbose_name='Testdaten'),
        ),
    ]
