# Generated by Django 5.2.12 on 2026-04-07 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0009_userexecution_testdata'),
        ('testcases', '0012_alter_testdata_options_testdata_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexecution',
            name='testdata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testcases.testdata', verbose_name='Testdaten'),
        ),
    ]
