# Generated by Django 4.2.17 on 2025-01-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('executions', '0002_initial'),
        ('windows', '0001_initial'),
        ('keywords', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.windowkeyword',),
        ),
        migrations.CreateModel(
            name='ActionExecution',
            fields=[
            ],
            options={
                'verbose_name': 'Execution',
                'verbose_name_plural': 'Execution',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('executions.keywordexecution',),
        ),
        migrations.CreateModel(
            name='ActionLibraryImport',
            fields=[
            ],
            options={
                'verbose_name': 'Library Import',
                'verbose_name_plural': 'Library Imports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('libraries.libraryimport',),
        ),
        migrations.CreateModel(
            name='RobotKeywordCall',
            fields=[
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
        migrations.CreateModel(
            name='ActionDocumentation',
            fields=[
            ],
            options={
                'verbose_name': 'Action Documentation',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='WindowAction',
            fields=[
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actions.action',),
        ),
    ]
