# Generated by Django 4.2.17 on 2025-02-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_windowaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionExecution',
        ),
    ]
