# Generated by Django 4.2.19 on 2025-02-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_delete_actionexecution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionDocumentation',
        ),
        migrations.DeleteModel(
            name='ActionLibraryImport',
        ),
        migrations.DeleteModel(
            name='RobotKeywordCall',
        ),
        migrations.DeleteModel(
            name='WindowAction',
        ),
        migrations.CreateModel(
            name='ActionQuickAdd',
            fields=[
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actions.action',),
        ),
    ]
