# Generated by Django 4.2.18 on 2025-03-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_delete_actiondocumentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionQuickChange',
            fields=[
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('actions.action',),
        ),
    ]
