# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_actionquickchange'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Aktion', 'verbose_name_plural': 'Aktionen'},
        ),
        migrations.AlterModelOptions(
            name='actionquickadd',
            options={'verbose_name': 'Aktion', 'verbose_name_plural': 'Aktionen'},
        ),
        migrations.AlterModelOptions(
            name='actionquickchange',
            options={'verbose_name': 'Aktion', 'verbose_name_plural': 'Aktionen'},
        ),
    ]
