# Generated by Django 4.2.21 on 2025-07-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0033_alter_keywordcallparameter_robot_variable'),
        ('actions', '0007_alter_action_options_alter_actionquickadd_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionStep',
            fields=[
            ],
            options={
                'verbose_name': 'Schritt',
                'verbose_name_plural': 'Schritte',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
    ]
