# Generated by Django 4.2.21 on 2025-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0051_delete_teststep_alter_executionkeywordcall_options'),
        ('actions', '0008_actionstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionWindowRelation',
            fields=[
            ],
            options={
                'verbose_name': 'Zuweisung zur Maske',
                'verbose_name_plural': 'Zuweisungen zu Masken',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keyword_windows', models.Model),
        ),
    ]
