# Generated by Django 5.2.6 on 2025-10-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0009_actionwindowrelation'),
        ('keywords', '0053_delete_librarykeywordcall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryKeywordCallParameter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcallparameter',),
        ),
    ]
