from dataclasses import dataclass


@dataclass
class Icons:
    action:str = 'fa-solid fa-cubes-stacked'
    arg_kw_param = 'fa-solid fa-p'
    arg_return_value = 'fa-solid fa-circle-left'
    arg_template_variable_value = 'fa-solid fa-dice-four'
    arg_variable = 'fa-solid fa-r'
    clone: str = 'fa-solid fa-copy'
    column_values: str = 'fa-solid fa-bars'
    condition: str = 'fa-solid fa-code-fork'
    delete: str = 'fa-solid fa-trash-can'
    delete_rel: str = 'fa-solid fa-trash'
    edit: str = 'fa-solid fa-pencil'
    exec_fail: str = 'fa-solid fa-circle-xmark'
    exec_log: str = 'fa-regular fa-file-lines'
    exec_pass: str = 'fa-solid fa-circle-check'
    exec_settings: str = 'fa-solid fa-gear'
    exec_start: str = 'fa-solid fa-circle-play'
    execute: str = 'fa-solid fa-flag-checkered'
    go_to: str = 'fa-solid fa-up-right-from-square'
    kw_call_drag_handle: str = 'fa-solid fa-sort'
    kw_call_input_output: str = 'fa-solid fa-arrow-right-arrow-left'
    kw_call_no_input_no_output: str = 'fa-solid fa-minus'
    kw_call_only_input: str = 'fa-solid fa-arrow-right-long'
    kw_call_only_output: str = 'fa-solid fa-arrow-left-long'
    library: str = 'fa-solid fa-robot'
    library_import_args: str = 'fa-solid fa-list'
    library_update: str = 'fa-solid fa-circle-arrow-up'
    preview: str = 'fa-solid fa-image'
    preview_field: str = 'fa-solid fa-eye'
    related_widget_add: str = 'fa-solid fa-circle-plus'
    related_widget_change: str = 'fa-solid fa-magnifying-glass'
    related_widget_delete: str = 'fa-solid fa-trash'
    related_widget_view: str = 'fa-solid fa-eye'
    reset_default_value: str = 'fa-solid fa-rotate-left'
    resource: str = 'fa-solid fa-key'
    save: str = 'fa-regular fa-floppy-disk'
    sequence: str = 'fa-solid fa-arrows-turn-to-dots'
    step_execute: str = 'fa-solid fa-square-check'
    step_begin_execution: str = 'fa-solid fa-arrow-right-from-bracket'
    step_end_execution: str = 'fa-solid fa-arrow-right-to-bracket'
    step_skip_execution: str = 'fa-solid fa-square-minus'
    system: str = 'fa-solid fa-shapes'
    testcase: str = 'fa-solid fa-list-check'
    unlink_rel: str = 'fa-solid fa-link-slash'
    update: str = 'fa-solid fa-rotate'
    variable: str = 'fa-solid fa-arrow-up-right-from-square'
    window: str = 'fa-solid fa-layer-group'
