# Generated by Django 4.2.17 on 2025-01-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('documentation', models.TextField(blank=True, verbose_name='Documentation')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('systems', models.ManyToManyField(related_name='testcases', to='systems.system', verbose_name='Systems')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
            },
        ),
    ]
