# Generated by Django 4.2.17 on 2025-01-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_delete_testcaseexecution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestStep',
        ),
    ]
