# Generated by Django 4.2.18 on 2025-03-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_delete_testcaseexecution_delete_teststep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['name'], 'verbose_name': 'Test Case', 'verbose_name_plural': 'Test Cases'},
        ),
    ]
