# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_alter_system_options_alter_system_attach_to_system_and_more'),
        ('testcases', '0004_alter_testcase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['name'], 'verbose_name': 'Testfall', 'verbose_name_plural': 'Testfälle'},
        ),
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='documentation',
            field=models.TextField(blank=True, verbose_name='Dokumentation'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='systems',
            field=models.ManyToManyField(related_name='testcases', to='systems.system', verbose_name='Systeme'),
        ),
    ]
