# Generated by Django 4.2.21 on 2025-06-06 12:02

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_alter_testcase_options_alter_testcase_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Testfall', 'verbose_name_plural': 'Testfälle'},
        ),
    ]
