# Generated by Django 4.2.21 on 2025-09-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0051_delete_teststep_alter_executionkeywordcall_options'),
        ('testcases', '0006_alter_testcase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStep',
            fields=[
            ],
            options={
                'verbose_name': 'Schritt',
                'verbose_name_plural': 'Schritte',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
    ]
