# Generated by Django 5.2.8 on 2026-01-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0009_alter_testcase_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': 'Testfall', 'verbose_name_plural': 'Testfälle'},
        ),
    ]
