# Generated by Django 5.2.11 on 2026-03-09 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0010_alter_testcase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('last_update', models.DateTimeField(null=True, verbose_name='Letzte Aktualisierung')),
                ('name', models.CharField(max_length=255)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testdata', to='testcases.testcase')),
            ],
            options={
                'verbose_name': 'Testdaten',
                'verbose_name_plural': 'Testdaten',
            },
        ),
    ]
