# Generated by Django 5.2.12 on 2026-04-07 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0011_testdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdata',
            options={'ordering': ['name'], 'verbose_name': 'Test Data', 'verbose_name_plural': 'Test Data'},
        ),
        migrations.AddField(
            model_name='testdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testdata',
            name='last_update',
            field=models.DateTimeField(null=True, verbose_name='Last Update'),
        ),
    ]
