# Generated by Django 4.2.17 on 2025-02-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_library_options_alter_libraryimport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryimport',
            options={'ordering': ['library__name'], 'verbose_name': 'Library Import', 'verbose_name_plural': 'Library Imports'},
        ),
    ]
