# Generated by Django 4.2.19 on 2025-03-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_alter_libraryimport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name'], 'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='library',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_library_name'),
        ),
    ]
