# Generated by Django 4.2.18 on 2025-03-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0004_alter_library_options_alter_library_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibraryKeyword',
        ),
        migrations.DeleteModel(
            name='LibraryKeywordDocumentation',
        ),
    ]
