# Generated by Django 4.2.20 on 2025-04-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_delete_librarykeyword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryimport',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.library', verbose_name='Library'),
        ),
    ]
