# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_alter_libraryimport_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name'], 'verbose_name': 'Bibliothek', 'verbose_name_plural': 'Bibliotheken'},
        ),
        migrations.AlterModelOptions(
            name='libraryimport',
            options={'ordering': ['library__name'], 'verbose_name': 'Bibliothek-Import', 'verbose_name_plural': 'Bibliothek-Imports'},
        ),
        migrations.AlterModelOptions(
            name='libraryparameter',
            options={'verbose_name': 'Einstellung', 'verbose_name_plural': 'Einstellungen'},
        ),
        migrations.AlterField(
            model_name='library',
            name='documentation',
            field=models.TextField(verbose_name='Dokumentation'),
        ),
        migrations.AlterField(
            model_name='library',
            name='init_doc',
            field=models.TextField(verbose_name='Einrichtung'),
        ),
        migrations.AlterField(
            model_name='libraryimport',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraries.library', verbose_name='Bibliothek'),
        ),
        migrations.AlterField(
            model_name='libraryimport',
            name='type',
            field=models.CharField(choices=[('FROM_EXECUTION', 'Aus einer Ausführung'), ('FROM_ACTION', 'Aus einer Aktion')], max_length=255),
        ),
        migrations.AlterField(
            model_name='libraryimportparameter',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Wert'),
        ),
        migrations.AlterField(
            model_name='libraryparameter',
            name='default_value',
            field=models.CharField(max_length=255, verbose_name='Standardwert'),
        ),
    ]
