# Generated by Django 4.2.21 on 2025-06-06 12:02

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_alter_library_options_alter_libraryimport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': [django.db.models.functions.text.Lower('name')], 'verbose_name': 'Bibliothek', 'verbose_name_plural': 'Bibliotheken'},
        ),
    ]
