# Generated by Django 4.2.21 on 2025-06-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0008_alter_library_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='libraryimport',
            name='library_import_sum_type',
        ),
    ]
