# Generated by Django 4.2.21 on 2025-08-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_remove_libraryimport_library_import_sum_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='typedocs',
            field=models.TextField(default='{}'),
        ),
    ]
