# Generated by Django 4.2.21 on 2025-08-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0010_library_typedocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryparameter',
            name='typedoc',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
