# Generated by Django 4.2.21 on 2025-08-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0011_libraryparameter_typedoc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryparameter',
            old_name='default_value',
            new_name='value',
        ),
    ]
