# Generated by Django 4.2.18 on 2025-02-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0002_delete_sequenceexecution'),
        ('resources', '0002_create_resource_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceResourceImport',
            fields=[
            ],
            options={
                'verbose_name': 'Resource Import',
                'verbose_name_plural': 'Resource Imports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.resourceimport',),
        )
    ]
