# Generated by Django 4.2.19 on 2025-02-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0004_delete_sequenceexecution'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SequenceDocumentation',
        ),
        migrations.DeleteModel(
            name='SequenceResourceImport',
        ),
        migrations.DeleteModel(
            name='WindowSequence',
        ),
        migrations.CreateModel(
            name='SequenceQuickAdd',
            fields=[
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sequences.sequence',),
        ),
    ]
