# Generated by Django 4.2.18 on 2025-03-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0005_delete_sequencedocumentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceQuickChange',
            fields=[
            ],
            options={
                'verbose_name': 'Sequence',
                'verbose_name_plural': 'Sequences',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sequences.sequence',),
        ),
    ]
