# Generated by Django 4.2.18 on 2025-03-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0006_sequencequickchange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionCall',
        ),
    ]
