# Generated by Django 4.2.21 on 2025-05-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sequences', '0007_delete_actioncall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sequence',
            options={'verbose_name': 'Sequenz', 'verbose_name_plural': 'Sequenzen'},
        ),
        migrations.AlterModelOptions(
            name='sequencequickadd',
            options={'verbose_name': 'Sequenz', 'verbose_name_plural': 'Sequenzen'},
        ),
        migrations.AlterModelOptions(
            name='sequencequickchange',
            options={'verbose_name': 'Sequenz', 'verbose_name_plural': 'Sequenzen'},
        ),
    ]
