# Generated by Django 4.2.21 on 2025-07-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0034_remove_keywordcall_condition_keywordcallcondition'),
        ('sequences', '0008_alter_sequence_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
            ],
            options={
                'verbose_name': 'Schritt',
                'verbose_name_plural': 'Schritte',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keywords.keywordcall',),
        ),
    ]
